# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Eric Liu
description:      Don't reinvent wheel. But must learn how to create.
url:              http://liuguangqiang.com
baseurl:          /
logo:             /content/images/me.png

author:
  name:           Eric Liu
  url:            https://github.com/liuguangqiang

paginate:         5

disqus_shortname: Eric Liu

github:
  repo:           https://github.com/liuguangqiang

# gems:
#   - jekyll-sitemap

twitter: '@liuguangqiang'

kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  input: GFM
