# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Eric
description:      Don't reinvent wheel. But you have to learn how to create.
url:              http://liuguangqiang.com
baseurl:          /
logo:             /content/images/me.png

author:
  name:           Eric
  url:            https://github.com/liuguangqiang

paginate:         10

disqus_shortname: guangqiang

# gems:
#   - jekyll-sitemap

twitter: '@lgq373779166'

github: liuguangqiang

linkedin: liuguangqiang

kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  input: GFM
